spring.application.name=api

# Core JDBC Data Source Properties
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password
spring.sql.init.mode=always

# Optional: Enable the web-based UI console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
